# Generated by Django 5.0.14 on 2026-09-02 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campana",
            name="ronda",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número de ronda dentro de una misma medición antes/después (1 = primera corrida, 2 = después de la capacitación, etc.). Permite comparar campañas relacionadas en el dashboard (Fase 2).",
            ),
        ),
        migrations.AddField(
            model_name="mensajecampana",
            name="dato_ingresado",
            field=models.BooleanField(
                default=False,
                help_text="True si el empleado envió el formulario de la página falsa. Se registra SOLO el evento, nunca el valor capturado (ver CHECKLIST_SEGURIDAD.md).",
            ),
        ),
        migrations.AddField(
            model_name="mensajecampana",
            name="fecha_apertura",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mensajecampana",
            name="fecha_dato_ingresado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mensajecampana",
            name="link_falso_visible",
            field=models.URLField(
                blank=True,
                help_text="El link que el empleado VE en el cuerpo del mensaje (con apariencia de phishing). Al enviar, se enmascara con un <a href> real que apunta al endpoint de tracking — igual que en un ataque real.",
            ),
        ),
        migrations.AddField(
            model_name="mensajecampana",
            name="token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador impredecible usado en los enlaces de tracking de este mensaje — nunca se expone el id numérico interno.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="campana",
            name="creada_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Puede quedar vacío cuando la campaña la genera un comando o una tarea automática en vez de una persona desde el panel.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campanas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
