# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPhishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=80, unique=True)),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('dificultad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('cuerpo', models.TextField(help_text='Usa {variable} para los campos a personalizar.')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('senales_alerta', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'dificultad'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('consentimiento_explicito', models.BooleanField(default=False, help_text='Debe ser True para poder generar/enviar mensajes. Requisito ético y de mitigación de riesgo del proyecto — no editable desde el admin sin auditoría.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('antiguedad_meses', models.PositiveIntegerField(default=0)),
                ('capacitaciones_previas', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto_final', models.CharField(blank=True, max_length=200)),
                ('cuerpo_final', models.TextField()),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('abierto', models.BooleanField(default=False)),
                ('cayo', models.BooleanField(blank=True, help_text='null = aún sin resultado (Fase 2)', null=True)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='campaigns.campana')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='campaigns.perfilempleado')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.plantillaphishing')),
            ],
            options={
                'indexes': [models.Index(fields=['campana', 'empleado'], name='campaigns_m_campana_04cc7f_idx')],
            },
        ),
    ]
