# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('piloto', 'Piloto (sin costo)'), ('basico', 'Básico'), ('pro', 'Pro')], default='piloto', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
