# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login_exitoso', 'Login exitoso'), ('login_fallido', 'Login fallido'), ('campana_generada', 'Campaña generada'), ('campana_enviada', 'Campaña enviada'), ('exportacion_datos', 'Exportación de datos'), ('cambio_rol', 'Cambio de rol')], max_length=50)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['accion', 'creado_en'], name='audit_regis_accion_e7ccd2_idx')],
            },
        ),
    ]
