# Generated by Django 5.0.14 on 2026-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login_exitoso", "Login exitoso"),
                    ("login_fallido", "Login fallido"),
                    ("campana_generada", "Campaña generada"),
                    ("campana_enviada", "Campaña enviada"),
                    ("exportacion_datos", "Exportación de datos"),
                    ("cambio_rol", "Cambio de rol"),
                    ("simulacro_apertura", "Empleado abrió un simulacro"),
                    ("simulacro_clic", "Empleado hizo clic en un simulacro (cayó)"),
                    (
                        "simulacro_dato_ingresado",
                        "Empleado envió datos en la página falsa",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
