# Generated by Django 5.0.14 on 2026-07-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.FloatField(help_text='0.0 a 1.0 — probabilidad de caer en un simulacro.')),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('version_modelo', models.CharField(default='baseline-logreg-v1', max_length=50)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_riesgo', to='campaigns.perfilempleado')),
            ],
            options={
                'ordering': ['-probabilidad'],
            },
        ),
    ]
